@HostAddressRoot = https://localhost:7293

GET {{HostAddressRoot}}/api/destinations?searchFor=a
Accept: application/json

### 

GET {{HostAddressRoot}}/api/destinations
Accept: application/json

### 

GET {{HostAddressRoot}}/api/itineraries?searchFor=Paris 
Accept: application/json
//Authorization: Bearer 

### 

GET {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
//Authorization: Bearer 

### 

GET {{HostAddressRoot}}/api/itineraries/11111
Accept: application/json


### 

POST {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
Content-type: application/json
//Authorization: Bearer 

{
    "name": "A stop for testing v2",
    "imageUri": "https://localhost:7293/images/1.jpg"
}

### 

PUT {{HostAddressRoot}}/api/itineraries/1/stops/9
Accept: application/json
Content-type: application/json

{
    "name": "A stop for update"
}