@HostAddressRoot = https://localhost:7293

GET {{HostAddressRoot}}/api/destinations?searchFor=a
Accept: application/json

### 

GET {{HostAddressRoot}}/api/destinations
Accept: application/json

### 

GET {{HostAddressRoot}}/api/itineraries?searchFor=Paris 
Accept: application/json
//Authorization: Bearer 

### 

GET {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
//Authorization: Bearer 

### 

GET {{HostAddressRoot}}/api/itineraries/11111
Accept: application/json


### 

POST {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBldGFyIiwic3ViIjoicGV0YXIiLCJqdGkiOiJhZTc3MDNjMSIsImF1ZCI6InRyYXZlbGluc3BpcmF0aW9uLWFwaSIsIm5iZiI6MTcyMjc2MTA4OSwiZXhwIjoxNzMwNzA5ODg5LCJpYXQiOjE3MjI3NjEwOTAsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.5fNYMNKMNK_pN4KnPegI-yB0hGzB-seC3H2762Ks8Xs

{
    "name": "A stop for testing",
    "imageUri": "https://localhost:7293/images/1.jpg"
}

### 

PUT {{HostAddressRoot}}/api/itineraries/1/stops/9
Accept: application/json
Content-type: application/json

{
    "name": "A stop for update"
}